### ISSUE TITLE
🐞 Storybook 7 with Master 2 and Vite

### ISSUE THREAD

**Issue by itsezc** [master-co/css#108]
### What happened?

The `@master/css.vite` causes issues with Storybook 7:

Vite config:
```ts
import MasterCSS from '@master/css.vite';

/** @type {import('vite').UserConfig} */
export default {
	plugins: [MasterCSS({ debug: true })],
};
```

### Version

2.0.0-beta.84

### Relevant log output

```shell
WARN Force closed manager build
ERR! TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
ERR!     at __node_internal_captureLargerStackTrace (node:internal/errors:491:5)
ERR!     at new NodeError (node:internal/errors:400:5)
ERR!     at validateString (node:internal/validators:163:11)
ERR!     at Object.dirname (node:path:1280:5)
ERR!     at o (/home/chiru/projects/foretag/node_modules/@master/css.vite/dist/index.cjs:1:748)
ERR!     at Context.buildStart (/home/chiru/projects/foretag/node_modules/@master/css.vite/dist/index.cjs:1:1310)
ERR!     at hookParallel (file:///home/chiru/projects/foretag/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:40165:47)
ERR!     at Object.buildStart (file:///home/chiru/projects/foretag/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:40439:19)
ERR!     at file:///home/chiru/projects/foretag/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:62181:29
ERR!     at initServer (file:///home/chiru/projects/foretag/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:62188:11)
ERR!     at Module.createServer (file:///home/chiru/projects/foretag/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:62206:15)
ERR!     at Object.start (/home/chiru/projects/foretag/node_modules/@storybook/builder-vite/dist/index.js:162:9519)
ERR!     at async storybookDevServer (/home/chiru/projects/foretag/node_modules/@storybook/core-server/dist/cjs/dev-server.js:119:20)
ERR!     at async buildDevStandalone (/home/chiru/projects/foretag/node_modules/@storybook/core-server/dist/cjs/build-dev.js:114:31)
ERR!     at async withTelemetry (/home/chiru/projects/foretag/node_modules/@storybook/core-server/dist/cjs/withTelemetry.js:65:5)
ERR!     at async dev (/home/chiru/projects/foretag/node_modules/@storybook/cli/dist/generate.js:425:440)
ERR!  TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
ERR!     at __node_internal_captureLargerStackTrace (node:internal/errors:491:5)
ERR!     at new NodeError (node:internal/errors:400:5)
ERR!     at validateString (node:internal/validators:163:11)
ERR!     at Object.dirname (node:path:1280:5)
ERR!     at o (/home/chiru/projects/foretag/node_modules/@master/css.vite/dist/index.cjs:1:748)
ERR!     at Context.buildStart (/home/chiru/projects/foretag/node_modules/@master/css.vite/dist/index.cjs:1:1310)
ERR!     at hookParallel (file:///home/chiru/projects/foretag/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:40165:47)
ERR!     at Object.buildStart (file:///home/chiru/projects/foretag/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:40439:19)
ERR!     at file:///home/chiru/projects/foretag/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:62181:29
ERR!     at initServer (file:///home/chiru/projects/foretag/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:62188:11)
ERR!     at Module.createServer (file:///home/chiru/projects/foretag/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:62206:15)
ERR!     at Object.start (/home/chiru/projects/foretag/node_modules/@storybook/builder-vite/dist/index.js:162:9519)
ERR!     at async storybookDevServer (/home/chiru/projects/foretag/node_modules/@storybook/core-server/dist/cjs/dev-server.js:119:20)
ERR!     at async buildDevStandalone (/home/chiru/projects/foretag/node_modules/@storybook/core-server/dist/cjs/build-dev.js:114:31)
ERR!     at async withTelemetry (/home/chiru/projects/foretag/node_modules/@storybook/core-server/dist/cjs/withTelemetry.js:65:5)
ERR!     at async dev (/home/chiru/projects/foretag/node_modules/@storybook/cli/dist/generate.js:425:440) {
ERR!   code: 'ERR_INVALID_ARG_TYPE'
ERR! }
```

### What browsers are you seeing the problem on?

Firefox

**Comment by itsezc** [comment]
Resolved in `2.0.0-beta.94`
