### ISSUE TITLE
🐞 rollup-plugin-inject: failed to parse @master/css.vue/dist/CSSProvider.vue

### ISSUE THREAD

**Issue by 1aron** [master-co/css#261]
### Description

(inject plugin) rollup-plugin-inject: failed to parse C:/Users/User/Projects/Nieke/website/node_modules/@master/css.vue/dist/CSSProvider.vue.

### Reproduction

```console
C:\Users\User\Projects\Nieke\website>yarn generate
yarn run v1.22.19
$ nuxt generate
Nuxi 3.6.2                                                                                                    18:02:58
Nuxt 3.6.2 with Nitro 2.5.2                                                                                   18:02:58

[18:03:02]  WARN  Using experimental payload extraction for full-static output. You can opt-out by setting experimental.payloadExtraction to false.

i Building client...                                                                                          18:03:21
i vite v4.3.9 building for production...                                                                      18:03:21
i ✓ 272 modules transformed.                                                                                  18:03:28
i .nuxt/dist/client/manifest.json                         3.70 kB │ gzip:  0.62 kB                            18:03:29
i .nuxt/dist/client/_nuxt/default.a1f3d880.css            0.03 kB │ gzip:  0.05 kB                            18:03:29
i .nuxt/dist/client/_nuxt/error-500.aa16ed4d.css          1.95 kB │ gzip:  0.74 kB                            18:03:29
i .nuxt/dist/client/_nuxt/error-404.23f2309d.css          3.63 kB │ gzip:  1.12 kB                            18:03:29
i .nuxt/dist/client/_nuxt/swiper-vue.5a9197c8.css        17.54 kB │ gzip:  4.59 kB                            18:03:29
i .nuxt/dist/client/_nuxt/master.css.48a16379.js          0.17 kB │ gzip:  0.13 kB                            18:03:29
i .nuxt/dist/client/_nuxt/availability.baa453f8.js        0.34 kB │ gzip:  0.27 kB                            18:03:29
i .nuxt/dist/client/_nuxt/error-500.d305f968.js           1.92 kB │ gzip:  1.01 kB                            18:03:29
i .nuxt/dist/client/_nuxt/useDirectusItems.ba7cc68e.js    2.14 kB │ gzip:  0.68 kB                            18:03:29
i .nuxt/dist/client/_nuxt/error-404.661724f8.js           2.30 kB │ gzip:  1.19 kB                            18:03:29
i .nuxt/dist/client/_nuxt/default.a50fb839.js             2.71 kB │ gzip:  1.41 kB                            18:03:29
i .nuxt/dist/client/_nuxt/nuxt-link.cb30db38.js           4.39 kB │ gzip:  1.89 kB                            18:03:29
i .nuxt/dist/client/_nuxt/index.5b873211.js               9.52 kB │ gzip:  3.31 kB                            18:03:29
i .nuxt/dist/client/_nuxt/index.da2bf98d.js              59.80 kB │ gzip: 18.56 kB                            18:03:29
i .nuxt/dist/client/_nuxt/entry.5395af83.js              85.01 kB │ gzip: 30.46 kB                            18:03:29
i .nuxt/dist/client/_nuxt/swiper-vue.7f82ab6c.js        150.31 kB │ gzip: 51.33 kB                            18:03:29
i ✓ built in 8.24s                                                                                            18:03:29
√ Client built in 8278ms                                                                                      18:03:29
i Building server...                                                                                          18:03:29
i vite v4.3.9 building SSR bundle for production...                                                           18:03:29
i ✓ 127 modules transformed.                                                                                  18:03:32
i .nuxt/dist/server/_nuxt/default-styles.80245733.mjs          0.15 kB                                        18:03:32
i .nuxt/dist/server/_nuxt/error-404-styles.cf00f4cc.mjs        0.15 kB                                        18:03:32
i .nuxt/dist/server/_nuxt/error-500-styles.a001b7ed.mjs        0.15 kB                                        18:03:32
i .nuxt/dist/server/styles.mjs                                 0.56 kB                                        18:03:32
i .nuxt/dist/server/_nuxt/entry-styles.c7279a36.mjs            1.01 kB                                        18:03:32
i .nuxt/dist/server/_nuxt/entry-styles-3.mjs-1f6c366b.js       0.14 kB │ map:   0.11 kB                       18:03:32
i .nuxt/dist/server/_nuxt/entry-styles-6.mjs-a239422a.js       0.14 kB │ map:   0.11 kB                       18:03:32
i .nuxt/dist/server/_nuxt/entry-styles-8.mjs-51d134f6.js       0.14 kB │ map:   0.11 kB                       18:03:32
i .nuxt/dist/server/_nuxt/entry-styles-9.mjs-56ce54a7.js       0.14 kB │ map:   0.11 kB                       18:03:32
i .nuxt/dist/server/_nuxt/entry-styles-7.mjs-90b73a0a.js       0.14 kB │ map:   0.11 kB                       18:03:32
i .nuxt/dist/server/_nuxt/entry-styles-4.mjs-eb717581.js       0.14 kB │ map:   0.11 kB                       18:03:32
i .nuxt/dist/server/_nuxt/entry-styles-5.mjs-32efda07.js       0.14 kB │ map:   0.11 kB                       18:03:32
i .nuxt/dist/server/_nuxt/entry-styles-10.mjs-d0104003.js      0.14 kB │ map:   0.11 kB                       18:03:32
i .nuxt/dist/server/_nuxt/entry-styles-11.mjs-349360c2.js      0.14 kB │ map:   0.11 kB                       18:03:32
i .nuxt/dist/server/_nuxt/entry-styles-12.mjs-5efb4960.js      0.14 kB │ map:   0.11 kB                       18:03:33
i .nuxt/dist/server/_nuxt/entry-styles-15.mjs-7f4ae0ee.js      0.14 kB │ map:   0.11 kB                       18:03:33
i .nuxt/dist/server/_nuxt/entry-styles-13.mjs-662eac91.js      0.14 kB │ map:   0.11 kB                       18:03:33
i .nuxt/dist/server/_nuxt/entry-styles-14.mjs-d61b14eb.js      0.14 kB │ map:   0.11 kB                       18:03:33
i .nuxt/dist/server/_nuxt/default-styles-1.mjs-5d854e0b.js     0.20 kB │ map:   0.11 kB                       18:03:33
i .nuxt/dist/server/_nuxt/index-e12b288f.js                    0.22 kB │ map:   5.28 kB                       18:03:33
i .nuxt/dist/server/_nuxt/master.css-29b59bff.js               0.28 kB │ map:   0.66 kB                       18:03:33
i .nuxt/dist/server/_nuxt/island-renderer-01656868.js          1.16 kB │ map:   1.41 kB                       18:03:33
i .nuxt/dist/server/_nuxt/availability-e3ae1c19.js             1.19 kB │ map:   0.92 kB                       18:03:33
i .nuxt/dist/server/_nuxt/entry-styles-1.mjs-708498e6.js       1.77 kB │ map:   0.11 kB                       18:03:33
i .nuxt/dist/server/_nuxt/error-500-styles-1.mjs-0a86f27a.js   2.17 kB │ map:   0.12 kB                       18:03:33
i .nuxt/dist/server/_nuxt/error-500-5436a504.js                3.15 kB │ map:   3.79 kB                       18:03:33
i .nuxt/dist/server/_nuxt/error-404-styles-1.mjs-6ef6e240.js   3.86 kB │ map:   0.12 kB                       18:03:33
i .nuxt/dist/server/_nuxt/error-404-ad0c400b.js                4.05 kB │ map:   5.83 kB                       18:03:33
i .nuxt/dist/server/_nuxt/useDirectusItems-0c2c937e.js         4.24 kB │ map:   7.22 kB                       18:03:33
i .nuxt/dist/server/_nuxt/nuxt-link-7a607302.js                5.99 kB │ map:  13.21 kB                       18:03:33
i .nuxt/dist/server/_nuxt/default-d3dc6ef5.js                  6.40 kB │ map:   3.64 kB                       18:03:33
i .nuxt/dist/server/_nuxt/index-fe3088df.js                   18.13 kB │ map:  11.79 kB                       18:03:33
i .nuxt/dist/server/_nuxt/entry-styles-2.mjs-c5b27163.js      18.27 kB │ map:   0.13 kB                       18:03:33
i .nuxt/dist/server/server.mjs                                45.31 kB │ map: 102.49 kB                       18:03:33
i ✓ built in 3.72s                                                                                            18:03:33
√ Server built in 3816ms                                                                                      18:03:33
√ Generated public .output/public                                                                       nitro 18:03:33
i Initializing prerenderer                                                                              nitro 18:03:33

[18:03:38]  WARN  (inject plugin) rollup-plugin-inject: failed to parse C:/Users/User/Projects/Nieke/website/node_modules/@master/css.vue/dist/CSSProvider.vue. Consider restricting the plugin to particular files via options.includeq
[nitro 18:03:38]  ERROR  RollupError: Unexpected token (Note that you need plugins to import files that are not JavaScript)

1: <script setup lang="ts">
   ^
2:
3: import { MasterCSS, initRuntime, type Config } from '@master/css'

 ERROR  Unexpected token (Note that you need plugins to import files that are not JavaScript)                 18:03:38

  at error (/C:/Users/User/Projects/Nieke/website/node_modules/rollup/dist/es/shared/node-entry.js:2245:30)
  at Module.error (/C:/Users/User/Projects/Nieke/website/node_modules/rollup/dist/es/shared/node-entry.js:13584:16)
  at Module.tryParse (/C:/Users/User/Projects/Nieke/website/node_modules/rollup/dist/es/shared/node-entry.js:14310:25)
  at Module.setSource (/C:/Users/User/Projects/Nieke/website/node_modules/rollup/dist/es/shared/node-entry.js:13911:39)
  at ModuleLoader.addModuleSource (/C:/Users/User/Projects/Nieke/website/node_modules/rollup/dist/es/shared/node-entry.js:24439:20)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by 1aron** [comment]
You can also use the following alternative, which still has the effect of lazy loading.
```vue
<script setup lang="ts">
onMounted(async () => {
    const [{ initRuntime }, { default: config }] = await Promise.all([
        import('@master/css'),
        import('./master.css')
    ])
    initRuntime(config)
})
</script>

<template>
    <NuxtWelcome class="{font:32!;font:heavy!;my:20;ls:-.02em}_h1@sm" />
</template>
```
