### ISSUE TITLE
🐞 Default animations throw error on navigation in Svelte 

### ISSUE THREAD

**Issue by oskar-gmerek** [master-co/css#274]
### Description

If we add one of the default animations anywhere in the page1, and then navigate to page2, then client will throw error:
```sh
Uncaught TypeError: Cannot read properties of undefined (reading 'count')
    at o (index.bundle.mjs:1:55431)
    at _a.delete (index.bundle.mjs:1:55804)
    at MutationObserver.<anonymous> (index.bundle.mjs:1:53414)
```
    
This is not the case with the custom animations created in masterCSS config.

### Reproduction

1. `git clone https://github.com/oskar-gmerek/mastercss-pr-svelte-bug`
2. `git checkout animation-bug`
2. `bun install` (enjoy speed of bun) & `bun run dev` **OR** `bun install` & `bun run build` & `bun run preview`
3. Go to localhost in browser and open developers tools console
4. Click any link to navigate to other page and look at browser console
5. Remove animation `@fade|1s|infinite` from header and check again - no errors will appear in the console

### System Informations

Browser: Latest Brave Browser 
OS: macOS 14.0
Node: 18
Package manager: Bun 1.0.0

**Comment by oskar-gmerek** [comment]
Forget to mention that, in addition to error in console there is also broken styles (need to refresh page)
